station:
  id: raspberry-pi-station

mqtt:
  host: 192.168.1.1
  port: 1884
  keepalive: 60

temperature:
  mqtt_topic: sensor/temperature
  producer_time: 3.0
  consumer_time: 2.0

humidity:
  mqtt_topic: sensor/humidity
  producer_time: 3.0
  consumer_time: 2.0

pm25:
  mqtt_topic: sensor/pm25
  producer_time: 3.0
  consumer_time: 2.0

pm10:
  mqtt_topic: sensor/pm10
  producer_time: 3.0
  consumer_time: 2.0

co2:
  mqtt_topic: sensor/co2
  producer_time: 3.0
  consumer_time: 2.0

vocs:
  mqtt_topic: sensor/vocs
  producer_time: 3.0
  consumer_time: 2.0