station:
  id: raspberry-pi-station

mqtt:
  host: a1p4xmzac7ibxf-ats.iot.us-east-1.amazonaws.com
  port: 8883
#  host: 192.168.1.1
#  port: 1884
  keepalive: 60
  cert_filepath: certificate.pem.crt
  private_key_filepath: private.pem.key
  ca_filepath: root-CA.crt

temperature:
  mqtt_topic: sensor/temperature
  producer_time: 60
  consumer_time: 30

humidity:
  mqtt_topic: sensor/humidity
  producer_time: 60
  consumer_time: 30

pm25:
  mqtt_topic: sensor/pm25
  producer_time: 5
  consumer_time: 3

pm10:
  mqtt_topic: sensor/pm10
  producer_time: 5
  consumer_time: 3

co2:
  mqtt_topic: sensor/co2
  producer_time: 5
  consumer_time: 3

vocs:
  mqtt_topic: sensor/vocs
  producer_time: 5
  consumer_time: 3